//! Vendored tree-sitter-go grammar (0.25.0 plus Go 1.26 `new(expr)`).

use tree_sitter::Language;

#[allow(
    unsafe_code,
    reason = "single audited FFI to the vendored tree-sitter-go entrypoint"
)]
unsafe extern "C" {
    fn tree_sitter_go() -> *const ();
}

/// Tree-sitter language for the vendored Go grammar.
#[must_use]
#[allow(
    unsafe_code,
    reason = "wraps the CLI-generated tree_sitter_go pointer as Language"
)]
pub(crate) fn language() -> Language {
    // SAFETY: `tree_sitter_go` is generated by tree-sitter CLI 0.25.8 from the
    // grammar in this crate and returns a pointer to a static `TSLanguage`.
    unsafe { Language::from_raw(tree_sitter_go().cast()) }
}

#[cfg(test)]
mod tests {
    use super::language;
    use tree_sitter::{Node, Parser};

    fn parse(source: &str) -> tree_sitter::Tree {
        let mut parser = Parser::new();
        parser
            .set_language(&language())
            .expect("vendored Go grammar should load");
        parser.parse(source, None).expect("tree-sitter parse")
    }

    fn wrap_stmt(stmt: &str) -> String {
        format!("package p\nfunc F() {{\n\t{stmt}\n}}\n")
    }

    fn first_new_arg<'tree>(root: Node<'tree>, source: &str) -> Node<'tree> {
        fn walk<'tree>(node: Node<'tree>, source: &str) -> Option<Node<'tree>> {
            if node.kind() == "call_expression"
                && node
                    .child_by_field_name("function")
                    .is_some_and(|function| source.get(function.byte_range()) == Some("new"))
            {
                return node
                    .child_by_field_name("arguments")
                    .and_then(|arguments| arguments.named_child(0));
            }
            let mut cursor = node.walk();
            let children: Vec<_> = node.children(&mut cursor).collect();
            for child in children {
                if let Some(found) = walk(child, source) {
                    return Some(found);
                }
            }
            None
        }
        walk(root, source).expect("new() call with a first argument")
    }

    #[test]
    fn language_should_load() {
        let mut parser = Parser::new();
        parser
            .set_language(&language())
            .expect("vendored Go grammar should load");
    }

    #[test]
    fn new_int_should_keep_type_identifier() {
        let source = wrap_stmt("var _ = new(int)");
        let tree = parse(&source);
        assert!(
            !tree.root_node().has_error(),
            "{}",
            tree.root_node().to_sexp()
        );
        assert_eq!(
            first_new_arg(tree.root_node(), &source).kind(),
            "type_identifier"
        );
    }

    #[test]
    fn new_int_literal_should_parse_as_expression() {
        let source = wrap_stmt("var _ = new(1)");
        let tree = parse(&source);
        assert!(
            !tree.root_node().has_error(),
            "{}",
            tree.root_node().to_sexp()
        );
        assert_eq!(
            first_new_arg(tree.root_node(), &source).kind(),
            "int_literal"
        );
    }

    #[test]
    fn new_qualified_type_should_keep_qualified_type() {
        let source = wrap_stmt("var _ = new(types.Cost)");
        let tree = parse(&source);
        assert!(
            !tree.root_node().has_error(),
            "{}",
            tree.root_node().to_sexp()
        );
        assert_eq!(
            first_new_arg(tree.root_node(), &source).kind(),
            "qualified_type"
        );
    }

    #[test]
    fn new_call_expression_should_parse() {
        let source = wrap_stmt("var _ = new(types.NewCost(0.35))");
        let tree = parse(&source);
        assert!(
            !tree.root_node().has_error(),
            "{}",
            tree.root_node().to_sexp()
        );
        assert_eq!(
            first_new_arg(tree.root_node(), &source).kind(),
            "call_expression"
        );
    }

    #[test]
    fn new_bare_identifier_should_stay_type_identifier() {
        let source = wrap_stmt("var _ = new(x)");
        let tree = parse(&source);
        assert!(
            !tree.root_node().has_error(),
            "{}",
            tree.root_node().to_sexp()
        );
        assert_eq!(
            first_new_arg(tree.root_node(), &source).kind(),
            "type_identifier"
        );
    }

    #[test]
    fn existing_go_fixtures_should_parse_without_error() {
        let fixtures =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures");
        let mut files = Vec::new();
        fn walk(dir: &std::path::Path, files: &mut Vec<std::path::PathBuf>) {
            let Ok(entries) = std::fs::read_dir(dir) else {
                return;
            };
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    walk(&path, files);
                } else if path.extension().is_some_and(|ext| ext == "go") {
                    files.push(path);
                }
            }
        }
        walk(&fixtures, &mut files);
        files.sort();
        assert!(
            !files.is_empty(),
            "expected Go fixtures under tests/fixtures"
        );
        let mut parser = Parser::new();
        parser
            .set_language(&language())
            .expect("vendored Go grammar should load");
        for path in files {
            let source = std::fs::read_to_string(&path).expect("read Go fixture");
            let tree = parser.parse(&source, None).expect("tree-sitter parse");
            assert!(
                !tree.root_node().has_error(),
                "{} should parse without ERROR: {}",
                path.display(),
                tree.root_node().to_sexp()
            );
        }
    }

    #[test]
    fn make_slice_should_keep_type_first_argument() {
        let source = wrap_stmt("var _ = make([]int, 1)");
        let tree = parse(&source);
        assert!(
            !tree.root_node().has_error(),
            "{}",
            tree.root_node().to_sexp()
        );
        let mut found = None;
        fn walk<'tree>(node: Node<'tree>, source: &str, found: &mut Option<Node<'tree>>) {
            if node.kind() == "call_expression"
                && node
                    .child_by_field_name("function")
                    .is_some_and(|function| source.get(function.byte_range()) == Some("make"))
            {
                *found = node
                    .child_by_field_name("arguments")
                    .and_then(|arguments| arguments.named_child(0));
                return;
            }
            let mut cursor = node.walk();
            let children: Vec<_> = node.children(&mut cursor).collect();
            for child in children {
                walk(child, source, found);
            }
        }
        walk(tree.root_node(), &source, &mut found);
        assert_eq!(found.expect("make() argument").kind(), "slice_type");
    }
}
